version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: bh_user
      POSTGRES_PASSWORD: bh_password
      POSTGRES_DB: bh_db
  #    ports:
  #      - "5432:5432"
  #    volumes:
  #      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: django_container
    ports:
      - "8123:8123"  # You can adjust this port as needed
    depends_on:
      db:
        condition: service_started
    env_file: ".env"
    volumes:
      - /Users/renaisun/Project/blockhouse/logs:/app/logs
#      - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydatabase


volumes:
  postgres_data:
