# Generated by Django 5.1.2 on 2024-10-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=40)),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=40)),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=40)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=40)),
                ('volume', models.IntegerField()),
            ],
        ),
    ]
