# Generated by Django 5.1.2 on 2024-10-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_data', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dailystockprice',
            index=models.Index(fields=['date'], name='date_idx'),
        ),
        migrations.AddIndex(
            model_name='dailystockprice',
            index=models.Index(fields=['stock_symbol'], name='stock_symbol_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailystockprice',
            constraint=models.UniqueConstraint(fields=('stock_symbol', 'date'), name='unique_stock_code_date'),
        ),
    ]
